export const employees = [
  {
    id: '1',
    name: 'Jose',
    last_name: 'Mendez',
    position: 'Software Developer',
    team: 'Product Development',
    performance: 80,
    contributionHistory: 20,
    budgetLeft: 500,
    picture: '/assets/yo.jpg',
    goals: [
      {
        id: '1',
        partner: 'Apple',
        partnerImg: '/assets/apple_logo.png',
        goal: 'Macbook Pro',
        description: '',
        totalAmount: 2000,
        partnerContribution: '05.00%',
        contributions: 100,
      },
      {
        id: '2',
        partner: 'Expedia',
        partnerImg: '/assets/expedia_logo.png',
        goal: 'Travel to Paris',
        description: '',
        totalAmount: 5000,
        partnerContribution: '05.00%',
        contributions: 500,
      },
      // {
      //   id: '3',
      //   partner: 'Toyota',
      //   partnerImg: 'src/assets/toyota_logo.png',
      //   goal: 'Car',
      //   description: 'I need the downpayment for a new car',
      //   totalAmount: 10000,
      //   partnerContribution: '05.00%',
      //   contributions: 1000,
      // },
    ],
  },
  {
    id: '2',
    name: 'Arjun',
    last_name: 'Purohit',
    position: 'Product Owner',
    team: 'Product Development',
    performance: 50,
    contributionHistory: 0,
    budgetLeft: 0,
    picture: '',
    goals: [
      // {
      //   id: '1',
      //   partner: 'Aamzon',
      //   partnerImg: 'src/assets/apple_logo.png',
      //   goal: 'Amazon Gift Card',
      //   description: 'I want to buy some stuff in Amazon',
      //   totalAmount: 1000,
      //   partnerContribution: '05.00%',
      //   contributions: 100,
      // },
      // {
      //   id: '2',
      //   partner: 'Expedia',
      //   partnerImg: 'src/assets/expedia_logo.png',
      //   goal: 'Travel',
      //   description: 'I am planning a trip to New York',
      //   totalAmount: 5000,
      //   partnerContribution: '05.00%',
      //   contributions: 500,
      // },
      // {
      //   id: '3',
      //   partner: 'Toyota',
      //   partnerImg: 'src/assets/toyota_logo.png',
      //   goal: 'Car',
      //   description: 'I need the downpayment for a new car',
      //   totalAmount: 10000,
      //   partnerContribution: '05.00%',
      //   contributions: 1000,
      // },
    ],
  },
  // {
  //   id: '3',
  //   name: 'Jiten',
  //   last_name: 'Thummar',
  //   position: 'Sales Lead',
  //   team: 'Sales',
  //   performance: 70,
  //   contributionHistory: 90,
  //   budgetLeft: 300,
  //   picture: 'src/assets/yo.jpg',
  //   goals: [
  //     {
  //       id: '1',
  //       partner: 'Apple',
  //       partnerImg: 'src/assets/apple_logo.png',
  //       goal: 'Macbook Pro',
  //       description: 'I need a personal macbook',
  //       totalAmount: 2000,
  //       partnerContribution: '05.00%',
  //       contributions: 100,
  //     },
  //     {
  //       id: '2',
  //       partner: 'Expedia',
  //       partnerImg: 'src/assets/expedia_logo.png',
  //       goal: 'Travel',
  //       description: 'I am planning a trip to New York',
  //       totalAmount: 5000,
  //       partnerContribution: '05.00%',
  //       contributions: 500,
  //     },
  //     {
  //       id: '3',
  //       partner: 'Toyota',
  //       partnerImg: 'src/assets/toyota_logo.png',
  //       goal: 'Car',
  //       description: 'I need the downpayment for a new car',
  //       totalAmount: 10000,
  //       partnerContribution: '05.00%',
  //       contributions: 1000,
  //     },
  //   ],
  // },
  // {
  //   id: '4',
  //   name: 'Abhinav',
  //   last_name: 'Lastname',
  //   position: 'Site Reliability Engineer',
  //   team: 'Product Development',
  //   performance: 80,
  //   contributionHistory: 100,
  //   budgetLeft: 200,
  //   picture: 'src/assets/yo.jpg',
  //   goals: [
  //     {
  //       id: '1',
  //       partner: 'Airbnb',
  //       partnerImg: 'src/assets/airbnb_logo.png',
  //       goal: 'Lodging',
  //       description: 'I need accommodation for my trip to Europe',
  //       totalAmount: 2000,
  //       partnerContribution: '05.00%',
  //       contributions: 100,
  //     },
  //     {
  //       id: '2',
  //       partner: 'Expedia',
  //       partnerImg: 'src/assets/expedia_logo.png',
  //       goal: 'Travel',
  //       description: 'I am planning a trip to Europe',
  //       totalAmount: 10000,
  //       partnerContribution: '05.00%',
  //       contributions: 500,
  //     },
  //     {
  //       id: '3',
  //       partner: 'Toyota',
  //       partnerImg: 'src/assets/toyota_logo.png',
  //       goal: 'Car',
  //       description: 'I need the downpayment for a new car',
  //       totalAmount: 10000,
  //       partnerContribution: '05.00%',
  //       contributions: 1000,
  //     },
  //   ],
  // },
]
